<?php
/**
 * Created by PhpStorm.
 * User: Lyunp
 * Date: 2019/10/17
 * Time: 9:09
 */

namespace app\mall\controller;


use app\common\controller\Mall;
use app\common\model\AppConfig;
use app\common\model\Buyer;
use think\helper\hash\Md5;

class WxCoupon extends Mall
{

    protected $appId; //公用ID

    protected $secret; //

    protected $mchId; //商户号

    protected $keys;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //读取小程序配置项
        $wx = (new AppConfig())->find();
        $this->appId    = $wx->wx_app_id;
        $this->secret   = $wx->wx_app_secret;
        $this->mchId    = $wx->wx_mchid;
        $this->keys     = $wx->wx_pay_key;
    }

    public function index()
    {
        return $this->fetch();
    }

    public function send()
    {
        return $this->fetch();
    }


    public function postTest()
    {
        $url = "https://api.mch.weixin.qq.com/mmpaymkttransfers/send_coupon";
        //组装参数
        $params = [
            'appid' => $this->appId,//公众账号ID
            'coupon_stock_id' => "9587103",//代金券批次id
            'mch_id' => $this->mchId,//商户号
            'nonce_str' => random(18),//随机字符串
            'openid' => $this->getUserInfo()->wx_open_id,//用户openid
            'openid_count' => 2,//openid记录数
            'partner_trade_no' => $this->mchId.date("Ymd").$this->getUserInfo()->buyer_id,//商户单据号
        ];
        ksort($params);
        $string1 = '';
        foreach($params as $k => $v) {
            $string1 .= "{$k}={$v}&";
        }
        $string1 .= 'key='.$this->keys;
        $params['sign'] = strtoupper(md5($string1));

        $xml = arrayToXml($params);
        echo $string1;
        dump($xml);
        $extras = array();
        //此处为证书位置（绝对路径），改成适合自己的，我这里放的比较那啥。。。。忽略///pxjiancai.com
        $extras['CURLOPT_SSLCERT'] = dirname(ROOT_PATH).'/pxjiancai.com/' . 'cret/apiclient_cert.pem';
        $extras['CURLOPT_SSLKEY']  = dirname(ROOT_PATH).'/pxjiancai.com/' . 'cret/apiclient_key.pem';

        dump($params['sign']);

        $res = CurlPostSsl($url,$xml,$extras);

        dump($res);
//        //返回信息
//        if($res){
//            $rsxml = simplexml_load_string($res);
//            if($rsxml->return_code == 'SUCCESS' && $rsxml->result_code == 'SUCCESS'){
//                return array('code'=>1,'msg'=>'发放成功');
//            }else{
//                //这里你可以获取，并返回详细失败信息，我这里都用这种方式返回了。
//                return array('code'=>0,'msg'=>'#1未知错误，稍后再试');
//            }
//        }else{
//            $error = curl_errno($ch);
//            curl_close($ch);
//            return array('code'=>0,'msg'=>$error );
//        }

    }


    public function getUserInfo()
    {
        return (new Buyer())->where('buyer_id','6')->field('buyer_id,wx_open_id')->find();
    }


    public function sign()
    {
        
    }

}